# Generated by Django 5.0 on 2023-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adiestrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('contacto', models.IntegerField()),
                ('barrio1', models.CharField(max_length=30)),
                ('barrio2', models.CharField(max_length=30)),
                ('barrio3', models.CharField(max_length=30)),
                ('barrio4', models.CharField(blank=True, max_length=30, null=True)),
                ('barrio5', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'adiestrador',
                'verbose_name_plural': 'adiestradores',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField()),
                ('opinion1', models.TextField(max_length=150)),
                ('opinion2', models.TextField(max_length=150)),
                ('opinion3', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'opinion',
                'verbose_name_plural': 'opiniones',
            },
        ),
    ]
