# Generated by Django 5.0 on 2023-12-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiestradores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.AddField(
            model_name='adiestrador',
            name='opinion1',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adiestrador',
            name='opinion2',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adiestrador',
            name='opinion3',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adiestrador',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
