# Generated by Django 5.0 on 2023-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiestradores', '0002_delete_opinion_adiestrador_opinion1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adiestrador',
            old_name='apellido',
            new_name='apellido_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='barrio1',
            new_name='barrio1_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='barrio2',
            new_name='barrio2_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='barrio3',
            new_name='barrio3_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='barrio4',
            new_name='barrio4_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='barrio5',
            new_name='barrio5_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='descripcion',
            new_name='descripcion_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='nombre',
            new_name='nombre_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='password',
            new_name='password_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='contacto',
            new_name='telefono_a',
        ),
        migrations.RenameField(
            model_name='adiestrador',
            old_name='usuario',
            new_name='usuario_a',
        ),
        migrations.AddField(
            model_name='adiestrador',
            name='mail_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
