# Generated by Django 5.0 on 2023-12-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiestradores', '0003_rename_apellido_adiestrador_apellido_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiestrador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
