# Generated by Django 5.0 on 2023-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiestradores', '0004_alter_adiestrador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiestrador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adiestrador',
            name='mail_a',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adiestrador',
            name='telefono_a',
            field=models.PositiveIntegerField(),
        ),
    ]
